export default {
  SMURF_TO_ADD_NAME_CHANGE: 'SMURF_TO_ADD_NAME_CHANGE',
  SMURF_TO_ADD_AGE_CHANGE: 'SMURF_TO_ADD_AGE_CHANGE',
  SMURF_TO_ADD_HEIGHT_CHANGE: 'SMURF_TO_ADD_HEIGHT_CHANGE',
  GET_SMURFS: 'GET_SMURFS'
}